spring:
  application:
    name: generic-order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    password: mypass
    username: postgres
    hikari:
      schema: order
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
feign:
  url: ${FEIGN_URL:http://localhost:8082}
server:
  port: 8081