spring:
  application:
    name: generic-order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: mypass
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8081